name: Deploy SSM File

on:
  push:
    branches:
      - main

jobs:
  ssm-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run SSM Command
        run: |
          INSTANCE_ID="${{ secrets.INSTANCE_ID }}"

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "SSM test - create file" \
            --parameters commands='[
              "echo \"I was here\" | sudo tee /home/ubuntu/Jaiho.txt",
              "ls -l /home/ubuntu/Jaiho.txt",
              "cat /home/ubuntu/Jaiho.txt"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID"
        shell: bash
